server:
  port: 8080
  context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: postgresdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # validate
#    show-sql: true